services:
  db:
    image: mysql:9.6
    container_name: petclinic-db
    env_file:
      - .db.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: petclinic
    #   MYSQL_USER: petclinic
    #   MYSQL_PASSWORD: petclinic
    volumes:
      - petclinic-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-upetclinic", "-ppetclinic"]
      interval: 10s
      timeout: 5s
      retries: 10          # increased retries
      start_period: 30s    # give MySQL time before healthcheck even starts

  app:
    build: .
    image: baselabouelnour/spring-petclinic:v1
    container_name: petclinic-app
    ports:
      - "8080:8080"
    env_file:
      - .app.env
    # environment:
    #   MYSQL_URL: jdbc:mysql://db:3306/petclinic   # "db" must match the service name above
    #   MYSQL_USER: petclinic
    #   MYSQL_PASS: petclinic
    #   SPRING_SQL_INIT_MODE: always
    #   SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure    # if app starts before MySQL is ready, Docker will retry it

volumes:
  petclinic-data: