# MYSQL_URL=jdbc:mysql://db:3306/petclinic   
# MYSQL_USER=petclinic
# MYSQL_PASS=petclinic
# SPRING_SQL_INIT_MODE=always
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
type: Opaque
stringData:
  MYSQL_URL: "jdbc:mysql://mysql-service:3306/petclinic"
  MYSQL_USER: "petclinic"
  MYSQL_PASS: "petclinic"
  SPRING_SQL_INIT_MODE: "always"